
apiVersion: v1
kind: Service
metadata:
  name: messaging-chat-service
  namespace: hb
spec:
  selector:
    app: messaging-chat-pod
  ports:
    - protocol: TCP
      port: 8302
      targetPort: 8302
  type: LoadBalancer
