apiVersion: v1
kind: Service
metadata:
  name: promtor-service
  namespace: bt
spec:
  selector:
    app: promtor-pod
  ports:
    - protocol: TCP
      port: 8007
      targetPort: 80
  type: LoadBalancer