
apiVersion: v1
kind: Service
metadata:
  name: evtracker-service
spec:
  selector:
    app: evtracker-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
