
apiVersion: v1
kind: Service
metadata:
  name: voltmate-site-service
spec:
  selector:
    app: voltmate-site-pod
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80
  type: LoadBalancer
