apiVersion: v1
kind: Service
metadata:
  name: axiupdeveloper-service
  namespace: bt
spec:
  selector:
    app: axiupdeveloper-pod
  ports:
    - protocol: TCP
      port: 8009
      targetPort: 80
  type: LoadBalancer