apiVersion: v1
kind: Service
metadata:
  name: apigateway-axilcorps-service
spec:
  selector:
    app: apigateway-axilcorps-pod
  ports:
    - protocol: TCP
      port: 6093
      targetPort: 8090
  type: LoadBalancer
