
apiVersion: v1
kind: Service
metadata:
  name: bs-multifilereader-service
spec:
  selector:
    app: bs-multifilereader-pod
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 80
  type: LoadBalancer
