apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: db
type: Opaque
data:
  mongodb-root-username: Y29uZmVldC1jaGF0LXVzZXI=
  mongodb-root-password: Y29uZmVldC1jaGF0XzAwMTJ4eV9hYmNAaTkwMDEyM2ti
