apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  namespace: kafka
spec:
  serviceName: kafka-broker-service
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-broker-service.kafka.svc.cluster.local"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_CREATE_TOPICS
          value: "attendance_request_action:1:1"
        # - name: KAFKA_LOG_DIRS
        #   value: /kafka/kafka-logs
        - name: KAFKA_BROKER_ID
          value: "1"
        # - name: KAFKA_JMX_PORT
        #   value: "5555"
        - name: KAFKA_CLEANUP_POLICY
          value: "compact"
      #   volumeMounts:
      #     - name: kafka-volume
      #       mountPath: "/kafka/kafka-logs"
      # volumes:
      #     - name: kafka-volume
      #       hostPath:
      #         path: /home/bot/ems/kafka-k8s/kafka-logs

--- 

apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
  namespace: kafka
  labels:
    app: kafka-broker-service
spec:
  type: LoadBalancer
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-broker