apiVersion: v1
kind: ServiceAccount
metadata:
  name: hb-gateway-sa
  namespace: hb

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hb-gateway-discovery-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hb-gateway-discovery-binding
subjects:
  - kind: ServiceAccount
    name: hb-gateway-sa
    namespace: hb
roleRef:
  kind: ClusterRole
  name: hb-gateway-discovery-role
  apiGroup: rbac.authorization.k8s.io
