
apiVersion: v1
kind: Service
metadata:
  name: bs-filegen-service
spec:
  selector:
    app: bs-filegen-pod
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 80
  type: LoadBalancer
