apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-rep
spec:
  ports:
  - protocol: TCP
    port: 27018
    targetPort: 27017
    nodePort: 30002
  selector:
    app: mongodb
  # type: LoadBalancer
  type: NodePort
