apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
  namespace: bt
spec:
  volumeName: files-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi