apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll-pod
  namespace: ems
  labels:
    app: payroll-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll-pod
  template:
    metadata:
      labels:
        app: payroll-pod
    spec:
      containers:
        - name: payroll-pod
          image: bottomhalflimited/ems.svc.payroll:emstum
          imagePullPolicy: Always
          ports:
            - containerPort: 8080