apiVersion: v1
kind: Service
metadata:
  name: payroll-service
  namespace: ems
spec:
  selector:
    app: payroll-pod
  ports:
    - protocol: TCP
      port: 8212
      targetPort: 8080
  type: NodePort
