apiVersion: v1
kind: Service
metadata:
  name: salary-declaration-service
  namespace: ems
spec:
  selector:
    app: salary-declaration-pod
  ports:
    - protocol: TCP
      port: 8212
      targetPort: 8080
  type: NodePort
