apiVersion: v1
kind: PersistentVolume
metadata:
  name: livekit-recordings-pv
  namespace: cf
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/livekit/recordings