# emstum ui service with 3 set of replica
apiVersion: v1
kind: Service
metadata:
  name: emstum-ui-service
  namespace: ems
spec:
  selector:
    app: emstum-ui-pod
  ports:
    - name: http
      protocol: TCP
      port: 8203
      targetPort: 80
  type: LoadBalancer