apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-pod
  namespace: kt
  labels:
    app: core-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-pod
  template:
    metadata:
      labels:
        app: core-pod
    spec:
      containers:
        - name: core-pod
          image: bottomhalflimited/kt-svc-coreservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080