apiVersion: v1
kind: Service
metadata:
  name: resources-apigateway-service
  namespace: bt
spec:
  selector:
    app: resources-apigateway-pod
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8080
  type: LoadBalancer
