
apiVersion: v1
kind: Service
metadata:
  name: bt-server-keyvault-service
  namespace: bt
spec:
  selector:
    app: bt-server-keyvault-pod
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8080
  type: LoadBalancer
