apiVersion: v1
kind: Service
metadata:
  name: ems-apigateway-service
  namespace: ems
spec:
  selector:
    app: ems-apigateway-pod
  ports:
    - protocol: TCP
      port: 8201
      targetPort: 8080
  type: LoadBalancer
