apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
  namespace: ems
spec:
  selector:
    app: apigateway-pod
  ports:
    - protocol: TCP
      port: 8201
      targetPort: 8080
  type: LoadBalancer
