apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-pod
  namespace: ems
  labels:
    app: apigateway-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway-pod
  template:
    metadata:
      labels:
        app: apigateway-pod
    spec:
      containers:
        - name: apigateway-pod
          image: bottomhalflimited/ems.gtw.apigateway:emstum
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
