apiVersion: v1
kind: Service
metadata:
  name: axilcorps-api-service
spec:
  selector:
    app: axilcorps-api-pod
  ports:
    - protocol: TCP
      port: 6092
      targetPort: 8081
  type: LoadBalancer