apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: ems
spec:
  selector:
    app: project-pod
  ports:
    - protocol: TCP
      port: 8211
      targetPort: 8085
  type: NodePort