apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems-manage-org-ui-pod
  namespace: ems
  labels:
    app: ems-manage-org-ui-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-manage-org-ui-pod
  template:
    metadata:
      labels:
        app: ems-manage-org-ui-pod
    spec:
      containers:
        - name: ems-manage-org-ui-pod
          image: istiyaqmi9/ems_portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80