apiVersion: v1
kind: Service
metadata:
  name: ems-manage-org-ui-service
  namespace: ems
spec:
  selector:
    app: ems-manage-org-ui-pod
  ports:
    - protocol: TCP
      port: 8209
      targetPort: 80
  type: LoadBalancer