apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-emstum-pod
  namespace: ems
  labels:
    app: manager-emstum-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager-emstum-pod
  template:
    metadata:
      labels:
        app: manager-emstum-pod
    spec:
      containers:
        - name: manager-emstum-pod
          image: istiyaqmi9/ems_portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80