
apiVersion: v1
kind: Service
metadata:
  name: filemanager-service
spec:
  selector:
    app: filemanager-pod
  ports:
    - protocol: TCP
      port: 5011
      targetPort: 8080
  type: LoadBalancer
