apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 30001
  selector:
    app: mongodb
  # type: LoadBalancer
  type: NodePort
