apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim-rep
  namespace: default
spec:
  storageClassName: manual
  #volumeName: mongodb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
