apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-rep
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo-rep"