apiVersion: v1
kind: Service
metadata:
  name: axilcorps-auth-service
spec:
  selector:
    app: axilcorps-auth-pod
  ports:
    - protocol: TCP
      port: 6091
      targetPort: 8180
  type: LoadBalancer
