
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
  namespace: hb
spec:
  selector:
    app: userservice-hb-pod
  ports:
    - protocol: TCP
      port: 8105
      targetPort: 8105
  type: LoadBalancer
