apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: ems
spec:
  selector:
    app: configserver-pod
  ports:
    - protocol: TCP
      port: 8204
      targetPort: 8083
  type: NodePort