apiVersion: v1
kind: Service
metadata:
  name: pinkproject-service
  namespace: bt
spec:
  selector:
    app: pinkproject-pod
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 80
  type: LoadBalancer