apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtor-pod
  namespace: bt
  labels:
    app: promtor-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtor-pod
  template:
    metadata:
      labels:
        app: promtor-pod
    spec:
      containers:
        - name: promtor-pod
          image: bottomhalflimited/bt.svc.promtor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80