apiVersion: v1
kind: Service
metadata:
  name: exit-service
  namespace: ems
spec:
  selector:
    app: exit-pod
  ports:
    - protocol: TCP
      port: 8215
      targetPort: 8080
  type: LoadBalancer