apiVersion: apps/v1
kind: Deployment
metadata:
  name: exit-pod
  namespace: ems
  labels:
    app: exit-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exit-pod
  template:
    metadata:
      labels:
        app: exit-pod
    spec:
      containers:
        - name: exit
          image: bottomhalflimited/ems-svc-exit:ems-exit-20250714073250
          imagePullPolicy: Always
          ports:
            - containerPort: 8080