apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exception-files-pvc
  namespace: bt
spec:
  volumeName: exception-files-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi