apiVersion: v1
kind: PersistentVolume
metadata:
  name: exception-files-pv
  namespace: bt
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /root/kube.ws/exception_files
    type: DirectoryOrCreate