# deployment for hirinb bell ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ketor-pod
  namespace: kt
spec:
  selector:
    matchLabels:
      app: ketor-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: ketor-pod
    spec:
      containers:
      - name: ketor-pod
        image: bottomhalflimited/kt.app.web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80