
apiVersion: v1
kind: Service
metadata:
  name: apigateway-hiringbell-service
  namespace: hb
spec:
  selector:
    app: apigateway-hb-pod
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
  type: LoadBalancer
