apiVersion: v1
kind: Service
metadata:
  name: proxysql-service-dev
  namespace: pms
spec:
  type: NodePort

  externalTrafficPolicy: Local

  selector:
    app: proxysql

  ports:
    - name: mysql
      protocol: TCP
      port: 6033
      targetPort: 6033
      nodePort: 32033