apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice-pod
  namespace: bt
  labels:
    app: emailservice-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice-pod
  template:
    metadata:
      labels:
        app: emailservice-pod
    spec:
      containers:
        - name: emailservice-pod
          image: bottomhalflimited/emailmanager-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/exception_files
              name: exception-file-volume
            # - mountPath: /app/applications
            #   name: document-volume    
      volumes:
        - name: exception-file-volume
          persistentVolumeClaim:
            claimName: exception-files-pvc
        # - name: document-volume
        #   persistentVolumeClaim:
        #     claimName: document-pvc                      