apiVersion: v1
kind: Service
metadata:
  name: emailservice-service
  namespace: bt
spec:
  selector:
    app: emailservice-pod
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8080
  type: LoadBalancer
