
apiVersion: v1
kind: Service
metadata:
  name: webui-service
  namespace: hb
spec:
  selector:
    app: webui-pod
  ports:
    - protocol: TCP
      port: 8105
      targetPort: 80
  type: LoadBalancer
