
apiVersion: v1
kind: Service
metadata:
  name: session-chat-service
  namespace: hb
spec:
  selector:
    app: session-chat-pod
  ports:
    - protocol: TCP
      port: 8303
      targetPort: 8303
  type: LoadBalancer
