
apiVersion: v1
kind: Service
metadata:
  name: bt-filemanager-service
  namespace: bt
spec:
  selector:
    app: bt-filemanager-pod
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080
  type: LoadBalancer
