apiVersion: v1
kind: Service
metadata:
  name: iconicclub-service
  namespace: bt
spec:
  selector:
    app: iconicclub-pod
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 80
  type: LoadBalancer