apiVersion: v1
kind: Service
metadata:
  name: employee-performance-service
  namespace: ems
spec:
  selector:
    app: employee-performance-pod
  ports:
    - protocol: TCP
      port: 8210
      targetPort: 8081
  type: NodePort