
apiVersion: v1
kind: Service
metadata:
  name: mf-web-service
  namespace: mf
spec:
  selector:
    app: mf-web-pod
  ports:
    - protocol: TCP
      port: 8551
      targetPort: 80
  type: LoadBalancer
