apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-pvc
  namespace: ems
spec:
  volumeName: document-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi