apiVersion: v1
kind: PersistentVolume
metadata:
  name: document-pv
  namespace: ems
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /root/kube.ws/applications
    type: DirectoryOrCreate