apiVersion: v1
kind: Service
metadata:
  name: manager-emstum-service
  namespace: ems
spec:
  selector:
    app: manager-emstum-pod
  ports:
    - protocol: TCP
      port: 8209
      targetPort: 80
  type: LoadBalancer