apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-pod
  namespace: ems
  labels:
    app: auth-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
        - name: auth-pod
          image: bottomhalflimited/ems-svc-auth:emstum
          imagePullPolicy: Always
          ports:
            - containerPort: 8080