apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ems
spec:
  selector:
    app: auth-pod
  ports:
    - protocol: TCP
      port: 8202
      targetPort: 8080
  type: LoadBalancer
