apiVersion: v1
kind: PersistentVolume
metadata:
  name: hiringbell-applicationfiles-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /root/kube.ws/HiringBell/Volumn_and_claims/resources
    type: DirectoryOrCreate