apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hiringbell-applicationfiles-pvc
spec:
  volumeName: hiringbell-applicationfiles-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi