# deployment for hirinb bell ui
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emstum-ui-pod
  namespace: ems-dev
spec:
  selector:
    matchLabels:
      app: emstum-ui-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: emstum-ui-pod
    spec:
      containers:
      - name: emstum-ui-pod
        #image: istiyaqmi9/hiringbell-ui:latest
        image: istiyaqmi9/ems_emstum_ui:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8090