
apiVersion: v1
kind: Service
metadata:
  name: apigateway-chat-service
  namespace: hb
spec:
  selector:
    app: apigateway-chat-pod
  ports:
    - protocol: TCP
      port: 8301
      targetPort: 8301
  type: LoadBalancer
