apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-manager-pod
  namespace: ems
  labels:
    app: service-manager-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-manager-pod
  template:
    metadata:
      labels:
        app: service-manager-pod
    spec:
      containers:
        - name: service-manager-pod
          image: bottomhalflimited/ems-manage-organization:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80