apiVersion: v1
kind: Service
metadata:
  name: service-manager-service
  namespace: ems
spec:
  selector:
    app: service-manager-pod
  ports:
    - protocol: TCP
      port: 8208
      targetPort: 80
  type: LoadBalancer