apiVersion: v1
kind: Service
metadata:
  name: ems-manage-organization-service
  namespace: ems
spec:
  selector:
    app: ems-manage-organization-pod
  ports:
    - protocol: TCP
      port: 8208
      targetPort: 80
  type: LoadBalancer