apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: lets-encrypt
spec:
 acme:
   email: info@bottomhalf.in
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # Secret resource that will be used to store the account's private key.
     name: lets-encrypt-dns-kay
   # Add a single challenge solver, HTTP01 using nginx
   solvers:
   - dns01:
       webhook:
         groupName: acme.emstum.com
         solverName: godaddy
         config:
          apiKeySecretRef:
            name: godaddy-credentials
            key: apiKey
          apiSecretSecretRef:
            name: godaddy-credentials
            key: apiSecret
          production: true