apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emstum-wildcard-cert
  namespace: default
spec:
  secretName: emstum-tls
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  commonName: '*.emstum.com'
  dnsNames:
    - '*.emstum.com'
