apiVersion: v1
kind: Secret
metadata:
  name: livekit-keys
  namespace: cf
type: Opaque
stringData:
  LIVEKIT_API_KEY: APIJByNUPVKqDS8          # Base64 encoded 'ZGV2a2V5' value of "devkey"
  LIVEKIT_API_SECRET: mcv0eMRL9uSw3fAna0jkDjxs4ZKBvpAM5WV9k3fOvk4B   # Base64 encoded 'c2VjcmV0a2V5' value of "secretkey"
  LIVEKIT_EGRESS_API_KEY: lk_egress
  LIVEKIT_EGRESS_API_SECRET: 2a0ca4b219fc36bf775d1a61fe1114be
