apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
